# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: sdcross/cs450

pipelines:
  branches:
    dev2:
      - step:
          script: # Modify the commands below to build your repository
            - source cs450-setup
            - make
    default:
      - step:
          script: # Modify the commands below to build your repository
            - source cs450-setup
            - make